call plug#begin('~/.vim/plugged')

" VCS
Plug 'tpope/vim-fugitive'

" System
Plug 'rking/ag.vim', {'on': 'Ag'}
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-unimpaired'
Plug 'ervandew/supertab'
Plug 'techlivezheng/vim-plugin-minibufexpl'
Plug 'bling/vim-airline'
Plug 'benekastah/neomake'
Plug 'sickill/vim-pasta'
Plug 'christoomey/vim-tmux-navigator'
Plug 'Shougo/deoplete.nvim'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'grassdog/tagman.vim'
Plug 'tpope/vim-eunuch'
" Plain Text
Plug 'reedes/vim-pencil', {'for': ['text']}
Plug 'junegunn/goyo.vim', {'for': ['text']}
Plug 'amix/vim-zenroom2', {'for': ['text']}

" Syntaxes
Plug 'othree/html5.vim', {'for': ['html']}
Plug 'vim-scripts/HTML-AutoCloseTag', {'for': ['html', 'jsx']}
Plug 'kchmck/vim-coffee-script', {'for': ['coffee']}
Plug 'toadums/vim-cjsx', {'for': ['coffee']}
Plug 'pangloss/vim-javascript', {'for': ['javascript', 'haml']}
Plug 'mxw/vim-jsx', {'for': ['javascript']}
Plug 'cakebaker/scss-syntax.vim', {'for': ['scss', 'sass', 'haml']}
Plug 'digitaltoad/vim-jade', {'for': ['jade']}

" Ruby
Plug 'vim-ruby/vim-ruby', {'for': 'ruby'}
Plug 'tpope/vim-rails', {'for': 'ruby'}
Plug 'tpope/vim-endwise', {'for': 'ruby'}

" Themes
Plug 'altercation/vim-colors-solarized'
Plug 'chriskempson/vim-tomorrow-theme'
Plug 'morhetz/gruvbox'

call plug#end()

" Change leader
nnoremap <SPACE> <Nop>
let mapleader = " "
let g:mapleader = " "

" Wildmenu
set wildmenu
set wildmode=list:longest
set wildignore+=*/tmp/*,*.so,*.swp,*.zip
set wildignore+=.hg,.git,.svn                    " Version control
set wildignore+=*.aux,*.out,*.toc                " LaTeX intermediate files
set wildignore+=*.o,*.obj,*.exe,*.dll,*.manifest " compiled object files
set wildignore+=*.spl,*.sw?,*.DS_Store,*.luac,*.pyc,**.class
set wildignore+=bower_components,node_modules,vendor/bundle,public
set wildcharm=<Tab>

let g:netrw_liststyle= 1

" Resize splits when the window is resized
au VimResized * exe "normal! \<c-w>="

" Basics
set relativenumber                      " always show line numbers
set number                              " Show the currently line number
set hidden                              " Allow un-saved buffers in background
set clipboard=unnamed                   " Share system clipboard.
set backspace=indent,eol,start          " Make backspace behave normally.
set backupskip=/tmp/*,/private/tmp/*
set backupdir=/tmp/
set directory=/tmp/                     " swap files
set ffs=unix,dos,mac                    " Default file types
set nowrap                              " don't wrap lines
set showmatch                           " set show matching parenthesis
set hlsearch                            " highlight search terms
set incsearch                           " show search matches as you type
set history=1000                        " remember more commands and search history
set undolevels=1000                     " use many muchos levels of undo
set visualbell                          " don't beep
set noerrorbells                        " don't beep
set cc=100
set re=1

" Default background & theme
syntax enable
set background=dark
" colorscheme
color gruvbox

" Default Tabs & spaces
set tabstop=2     " a tab is two spaces
set shiftwidth=2  " number of spaces to use for autoindenting
set softtabstop=2
set expandtab
set shiftround    " use multiple of shiftwidth when indenting with '<' and '>'
set smarttab      " insert tabs on the start of a line according to
                  "    shiftwidth, not tabstop
set autoindent    " always set autoindenting on
set copyindent    " copy the previous indentation on autoindenting
set cursorline    " highlight current line

" Highlight VCS conflict markers
match ErrorMsg '^\(<\|=\|>\)\{7\}\([^=].\+\)\?$'

" I CAN HAZ NORMAL REGEXES?
nnoremap / /\v
vnoremap / /\v

" " (Hopefully) removes the delay when hitting esc in insert mode
" set noesckeys
" set ttimeout
" set ttimeoutlen=1

" Hide scrollbars
set guioptions=Ace

" Plugin Configurations
"""""""""""""""""""""""
filetype indent plugin on
autocmd BufNewFile,BufReadPost *.coffee setl foldmethod=indent nofoldenable foldlevel=1
au BufNewFile,BufRead *.cjsx set filetype=coffee

" Trim trailing whitespace on save
autocmd BufWritePre * :%s/\s\+$//e
let g:miniBufExplVSplit = 40
let g:miniBufExplSortBy = "mru"

autocmd! BufWritePost * Neomake
let g:neomake_javascript_enabled_makers = ['eslint']

""""""""""""""""""""""""""""""
" airline
""""""""""""""""""""""""""""""
let g:airline_powerline_fonts = 1
let g:airline_theme = 'gruvbox'

if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif

let g:airline_symbols.space = "\ua0"
let g:airline#enable#branch = 1

function! AirlineInit()
  let g:airline_section_x = 0
  let g:airline_section_y = 0
  let g:airline_section_z = airline#section#create_left(['filetype'])
endfunction
autocmd User AirlineAfterInit call AirlineInit()

" Auto highlight search result matches
let g:ag_highlight=1

let g:jsx_ext_required = 0

" vim pasta
let g:pasta_disabled_filetypes = ['python', 'coffee', 'yaml']

" deoplete
let g:deoplete#enable_at_startup = 1

" Gross hack to make c-h work to move left a split
if has('nvim')
  nmap <bs> <c-w>h
endif

" Default fzf layout
" - down / up / left / right
" - window (nvim only)
let g:fzf_height = '30%'

let g:tagman_auto_generate = 1

let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1

" Key Bindings
"""""""""""""""""""""""

" keybindings for easier switching between splits
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

"make < > shifts keep selection
vnoremap < <gv
vnoremap > >gv

" Leader maps
nnoremap <leader>f :FZF<CR>
nnoremap <leader>d :vsp %:h/<Tab>

nnoremap <leader><space> :noh<cr>
nnoremap <leader>gs :Gstatus<CR>
nnoremap <leader>gd :Gdiff<CR>
nnoremap <leader>gb :Gblame<CR>
nnoremap <leader>c  :ccl<CR>:lclose<CR>

nnoremap - :Explore<CR>

nnoremap <leader>j  :w<CR>
nnoremap <leader>b  :MBEToggle<CR>
nnoremap <leader>k  :MBEFocus<CR>

nnoremap \ :Ag!<SPACE>

nnoremap <leader>s <C-]>
nnoremap <leader>S :vsp<CR><C-]>

