set encoding=utf-8
set nocompatible

call plug#begin('~/.vim/plugged')

" VCS
Plug 'tpope/vim-fugitive'

" System
Plug 'rking/ag.vim', {'on': 'Ag'}
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-unimpaired'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'ervandew/supertab'
Plug 'techlivezheng/vim-plugin-minibufexpl'
Plug 'bling/vim-airline'
Plug 'benekastah/neomake'

" Plain Text
Plug 'reedes/vim-pencil', {'for': ['text']}
Plug 'junegunn/goyo.vim', {'for': ['text']}
Plug 'amix/vim-zenroom2', {'for': ['text']}

" Syntaxes
Plug 'othree/html5.vim', {'for': ['html']}
Plug 'vim-scripts/HTML-AutoCloseTag', {'for': ['html']}
Plug 'kchmck/vim-coffee-script', {'for': ['coffee']}
Plug 'toadums/vim-cjsx', {'for': ['coffee']}
Plug 'pangloss/vim-javascript', {'for': ['javascript', 'haml']}
Plug 'mxw/vim-jsx', {'for': ['javascript']}
Plug 'cakebaker/scss-syntax.vim', {'for': ['scss', 'sass', 'haml']}
Plug 'elixir-lang/vim-elixir'
Plug 'digitaltoad/vim-jade', {'for': ['jade']}

" Ruby
Plug 'vim-ruby/vim-ruby', {'for': 'ruby'}
Plug 'tpope/vim-rails', {'for': 'ruby'}
Plug 'tpope/vim-endwise', {'for': 'ruby'}

" Themes
Plug 'zenorocha/dracula-theme', {'rtp': 'vim/'}
Plug 'altercation/vim-colors-solarized'
Plug 'chriskempson/vim-tomorrow-theme'
Plug 'morhetz/gruvbox'
Plug 'nanotech/jellybeans.vim'

call plug#end()

" Change leader
nnoremap <SPACE> <Nop>
let mapleader = " "
let g:mapleader = " "

" Wildmenu
set wildmenu
set wildmode=list:longest
set wildignore+=*/tmp/*,*.so,*.swp,*.zip
set wildignore+=.hg,.git,.svn                    " Version control
set wildignore+=*.aux,*.out,*.toc                " LaTeX intermediate files
set wildignore+=*.o,*.obj,*.exe,*.dll,*.manifest " compiled object files
set wildignore+=*.spl,*.sw?,*.DS_Store,*.luac,*.pyc,**.class
set wildignore+=bower_components,node_modules,vendor/bundle,public

let g:netrw_liststyle= 1

" Resize splits when the window is resized
au VimResized * exe "normal! \<c-w>="

" Basics
set relativenumber                      " always show line numbers
set number                              " Show the currently line number
set hidden                              " Allow un-saved buffers in background
set clipboard=unnamed                   " Share system clipboard.
set backspace=indent,eol,start          " Make backspace behave normally.
set backupskip=/tmp/*,/private/tmp/*
set backupdir=/tmp/
set directory=/tmp//                    " swap files
set ffs=unix,dos,mac                    " Default file types
set nowrap                              " don't wrap lines
set showmatch                           " set show matching parenthesis
set hlsearch                            " highlight search terms
set incsearch                           " show search matches as you type
set history=1000                        " remember more commands and search history
set undolevels=1000                     " use many muchos levels of undo
set visualbell                          " don't beep
set noerrorbells                        " don't beep

" Default background & theme
syntax enable
set background=dark

" colorscheme
color gruvbox

" Default Tabs & spaces
set tabstop=2     " a tab is two spaces
set shiftwidth=2  " number of spaces to use for autoindenting
set softtabstop=2
set expandtab
set shiftround    " use multiple of shiftwidth when indenting with '<' and '>'
set smarttab      " insert tabs on the start of a line according to
                  "    shiftwidth, not tabstop
set autoindent    " always set autoindenting on
set copyindent    " copy the previous indentation on autoindenting

" Highlight VCS conflict markers
match ErrorMsg '^\(<\|=\|>\)\{7\}\([^=].\+\)\?$'

" I CAN HAZ NORMAL REGEXES?
nnoremap / /\v
vnoremap / /\v

" (Hopefully) removes the delay when hitting esc in insert mode
set noesckeys
set ttimeout
set ttimeoutlen=1

" Hide scrollbars
set guioptions=Ace

" Plugin Configurations
"""""""""""""""""""""""
filetype indent plugin on
autocmd BufNewFile,BufReadPost *.coffee setl foldmethod=indent nofoldenable foldlevel=1

let g:ctrlp_match_window = 'bottom,max:40'
let g:ctrlp_mruf_relative = 1
let g:ctrlp_user_command = 'ag %s -l -g ""'

" AG is so fast we dont need caching
let g:ctrlp_use_caching = 0

" Trim trailing whitespace on save
autocmd BufWritePre * :%s/\s\+$//e
let g:miniBufExplVSplit = 40
let g:miniBufExplSortBy = "mru"

autocmd! BufWritePost * Neomake
let g:neomake_javascript_enabled_makers = ['eslint']

""""""""""""""""""""""""""""""
" airline
""""""""""""""""""""""""""""""
let g:airline_theme             = 'tomorrow'
let g:airline#enable#branch     = 1
let g:airline#enable#syntastic  = 1

" vim-powerline symbols
let g:airline_left_sep          = '⮀'
let g:airline_left_alt_sep      = '⮁'
let g:airline_right_sep         = '⮂'
let g:airline_right_alt_sep     = '⮃'
let g:airline_branch_prefix     = '⭠'
let g:airline#readonly#symbol   = '⭤'
let g:airline#linecolumn#prefix = '⭡'

function! AirlineInit()
    let g:airline_section_a = airline#section#create(['mode'])
    let g:airline_section_b = airline#section#create_left(['branch'])
    let g:airline_section_c = airline#section#create(['%f'])
    let g:airline_section_x = airline#section#create([])
    let g:airline_section_y = airline#section#create(['filetype'])
    let g:airline_section_z = airline#section#create(['^_^'])
endfunction
autocmd VimEnter * call AirlineInit()

" Auto highlight search result matches
let g:ag_highlight=1

let g:jsx_ext_required = 0

" Gross hack to make c-h work to move left a split
if has('nvim')
  nmap <bs> <c-w>h
endif

" Key Bindings
"""""""""""""""""""""""

" keybindings for easier switching between splits
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

"make < > shifts keep selection
vnoremap < <gv
vnoremap > >gv

" Leader maps
nnoremap <leader>f :CtrlP<CR>
nnoremap <leader>d :vsp %:h/

nnoremap <leader><space> :noh<cr>
nnoremap <leader>s  :Ag!<Space>
nnoremap <leader>gs :Gstatus<CR>
nnoremap <leader>gd :Gdiff<CR>
nnoremap <leader>gb :Gblame<CR>
nnoremap <leader>c  :ccl<CR>:lclose<CR>

nnoremap - :Explore<CR>

nnoremap <leader>j  :w<CR>
nnoremap <leader>b  :MBEToggle<CR>
nnoremap <leader>k  :MBEFocus<CR>

nnoremap <silent> <leader>z :Goyo<cr>

